config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: [:session, :registrations] do
    get '/sign_in', to: 'devise/sessions#new', as: :new_user_session
    get '/sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
    get '/users/edit', to: 'devise/registrations#edit', as: :edit_user
    put '', to: 'devise/registrations#update'
  end
  root 'top#index'

  resources :payments, only: %w(index destroy) do
    collection do
      post 'confirm'
      delete 'bulk_destroy'
    end
  end

  resources :events do
    resources :items
  end

end

app/models/event.rb
require 'date'

class Event < ActiveRecord::Base
  has_many :participants
  has_many :users, through: :participants
  has_many :items
  has_many :payments, through: :items
  before_save :escape_tag

  validates :name, presence: true,  length: { maximum: 40 }

  validates :memo, presence: false, length: { maximum: 40 }

  default_scope -> { order('id DESC') }

  def formatted_date
    DateTime.parse(date.to_s).strftime('%Y/%m/%d').to_s if date
  end

  private

  def escape_tag
    tags = {
      '<' => '&lt;',
      '>' => '&gt;' }
    tags.each do |key, val|
      name.gsub!(key, val)
      memo.gsub!(key, val)
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.page params[:page]
    @participants = Participant.all
  end

  def new
    @event = Event.new
    @users = User.all
  end

  def show
    @event = Event.find(params[:id])
    @items = @event.items.page(params[:page]).per(5)
  end

  def create
    @event = Event.new(event_params)
    @users = User.all
    if @event.save
      if params[:event][:participant_ids]
        params[:event][:participant_ids].each do |p_id|
          @event.participants.create(user_id: p_id.to_i) unless p_id.empty?
        end
      end
      flash[:success] = "イベント#{@event.name}を作成しました"
      redirect_to @event
    else
      render 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
    @users = User.all
    @not_participate_users = @users - @event.users
  end

  def update
    @event = Event.find(params[:id])
    @users = User.all
    @not_participate_users = @users - @event.users
    if update_event
      add_participant
      redirect_to @event
    else
      render 'edit'
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :memo, :date)
  end

  def update_event
    @event.name = params[:event][:name]
    @event.memo = params[:event][:memo]
    @event.date = params[:event][:date]
    @event.save
  end

  def add_participant
    params[:event][:participant_ids].each do |p_id|
      @event.participants.create(user_id: p_id.to_i) unless p_id.empty?
    end if params[:event][:participant_ids]
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<% provide(:title, 'イベント編集') %>
<% provide(:datepicker_form, true) %>
<% breadcrumb :edit_event, @event %>
<div class="container">

  <div class="bs-docs-section">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
        <div class="page-header">
          <h1>イベント編集</h1>
        </div>
      </div>
    </div>
  </div>

  <div class="bs-docs-section">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
        <div class="well bs-component">
          <%= form_for @event, :html => { :class => 'form-horizontal', :role => 'form' } do |f| %>
            <% if @event.errors.any? %>
              <div class="alert alert-dismissable alert-danger">
                <strong>Error!</strong>
                <ul>
                  <% @event.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
            <% end%>
            <fieldset>
              <legend>イベント基本情報</legend>
              <div class="form-group">
                <div class="col-lg-2 control-label" data-toggle='popover' data-placement='top', title=' イベント名' data-trigger='hover' data-content='登録するイベント名を最大40文字で入力してください。'>
                  <%= f.label :name, 'イベント名' %>
                  <i class="glyphicon glyphicon-question-sign"></i>
                </div>
                <div class="col-lg-10">
                  <%= f.text_field :name, class: 'form-control', placeholder: 'イベント名を入力して下さい' %>
                </div>
              </div>
              <div class="form-group">
                <div class="col-lg-2 control-label" data-toggle='popover' data-placement='top', title='概要' data-trigger='hover' data-content='登録するイベントの概要を最大40文字で入力してください。'>
                  <%= f.label :memo, '概要' %>
                  <i class="glyphicon glyphicon-question-sign"></i>
                </div>
                <div class="col-lg-10">
                  <%= f.text_area :memo, class: 'form-control', placeholder: 'このイベントに関するメモを自由に入力して下さい' %>
                </div>
              </div>
              <div class="form-group">
                <div class="col-lg-2 control-label" data-toggle='popover' data-placement='top', title=' 開催日' data-trigger='hover' data-content='イベントが開催された日付を選択して下さい。'>
                  <%= f.label :date, '開催日' %>
                  <i class="glyphicon glyphicon-question-sign"></i>
                </div>
                <div class="col-lg-10">
                  <%= f.text_field :date, value: @event.formatted_date, class: 'form-control', type: 'text', placeholder: 'イベントが開催された日付を選択して下さい。', readonly: true %>
                </div>
              </div>
              <div class="form-group">
                <div class="col-lg-2 control-label" data-toggle='popover' data-placement='top', title=' 参加者' data-trigger='hover' data-content='参加このイベントに参加した参加者を選んでください。参加者リストに該当する参加者が存在しない場合は、先にユーザー登録を実施してください。'>
                  <%= f.label :participants, '参加者' %>
                  <i class="glyphicon glyphicon-question-sign"></i>
                </div>
                <div class="col-lg-10">
                  <% if @event.users.empty? %>
                    イベント参加中のユーザは存在しません
                  <% else %>
                    <ul>
                      <% @event.users.each do |u| %>
                        <li><%= u.name %></li>
                      <% end %>
                    </ul>
                  <% end %>
                </div>
                <div class="col-lg-10 col-lg-offset-2">
                  <% if @not_participate_users.empty? %>
                    イベント未参加のユーザは存在しません
                  <% else %>
                    <select class="form-control" id="event_participant_ids" multiple="multiple" name="event[participant_ids][]">
                      <option value="">追加する参加者を選択</option>
                      <% @not_participate_users.each do |u| %>
                        <option value="<%= u.id %>"><%= u.name %></option>
                      <% end %>
                    </select>
                  <% end %>
                </div>
              </div>
              <div class="form-group">
                <div class="form-group">
                  <div class="col-lg-10 col-lg-offset-2">
                    <%= f.submit '確定', class: 'btn btn-primary btn-lg' %>
                    <%= link_to '戻る', event_path(@event), class: 'btn btn-default btn-lg' %>
                  </div>
                </div>
              </div>
            </fieldset>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<% provide(:title, 'イベント一覧') %>
<% breadcrumb :events, @events %>
<div class="container">
  <div class="bs-docs-section">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
        <div class="page-header">
          <h1>イベント一覧</h1>
        </div>
      </div>
    </div>
  </div>

  <div class="bs-docs-section">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
        <div class="well bs-component">
          <%= link_to 'イベントを作るよ', {controller: :events, action: :new}, class: :"btn btn-primary btn-lg" %>
          <%= link_to '戻る', :root, class: :"btn btn-default btn-lg" %>
        </div>
      </div>
    </div>
  </div>

  <div class="bs-docs-section">
    <%= paginate @events %>
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
        <div class="well bs-component">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>イベント名</th>
                <th>参加者</th>
                <th>開催日</th>
              </tr>
            </thead>
            <tbody>
              <% @events.each do |event|%>
                <tr>
                  <td><%= link_to event.name, event, class: :"btn btn-link"%></td>
                  <td>
                    <% if event.users.blank? %>
                      (無し)
                    <% else %>
                      <%= event.users.count %>名
                    <% end %>
                  </td>
                  <td><%= event.formatted_date.blank? ? '(未入力)' : event.formatted_date %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <%= paginate @events %>
  </div>
</div>

app/views/events/new.html.erb
<% provide(:title, 'イベント作成') %>
<% provide(:datepicker_form, true) %>
<% breadcrumb :new_event, @event %>
<div class="container">

  <div class="bs-docs-section">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
        <div class="page-header">
          <h1>イベント作成</h1>
        </div>
      </div>
    </div>
  </div>

  <div class="bs-docs-section">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
        <div class="well bs-component">
          <%= form_for @event, :html => { :class => 'form-horizontal', :role => 'form' } do |f| %>
            <% if @event.errors.any? %>
              <div class="alert alert-dismissable alert-danger">
                <strong>Error!</strong>
                <ul>
                  <% @event.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
            <% end%>
            <fieldset>
              <div class="form-group">
                <div class="col-lg-2 control-label" data-toggle='popover' data-placement='top', title=' イベント名' data-trigger='hover' data-content='登録するイベント名を最大40文字で入力してください。'>
                  <%= f.label :name, 'イベント名' %>
                  <i class="glyphicon glyphicon-question-sign"></i>
                </div>
                <div class="col-lg-10">
                  <%= f.text_field :name, class: 'form-control', placeholder: 'イベント名を入力して下さい' %>
                </div>
              </div>
              <div class="form-group">
                <div class="col-lg-2 control-label" data-toggle='popover' data-placement='top', title='概要' data-trigger='hover' data-content='登録するイベントの概要を最大40文字で入力してください。'>
                  <%= f.label :memo, '概要' %>
                  <i class="glyphicon glyphicon-question-sign"></i>
                </div>
                <div class="col-lg-10">
                  <%= f.text_area :memo, class: 'form-control', placeholder: 'このイベントに関するメモを自由に入力して下さい' %>
                </div>
              </div>
              <div class="form-group">
                <div class="col-lg-2 control-label" data-toggle='popover' data-placement='top', title=' 開催日' data-trigger='hover' data-content='イベントが開催された日付を選択して下さい。'>
                  <%= f.label :date, '開催日' %>
                  <i class="glyphicon glyphicon-question-sign"></i>
                </div>
                <div class="col-lg-10">
                  <%= f.text_field :date, class: 'form-control', type: 'text', placeholder: 'このイベントの開催日を入力して下さい', readonly: true %>
                </div>
              </div>
              <div class="form-group">
                <div class="col-lg-2 control-label" data-toggle='popover' data-placement='top', title=' 参加者' data-trigger='hover' data-content='参加このイベントに参加した参加者を選んでください。参加者リストに該当する参加者が存在しない場合は、先にユーザー登録を実施してください。'>
                  <%= f.label :participants, '参加者' %>
                  <i class="glyphicon glyphicon-question-sign"></i>
                </div>
                <div class="col-lg-10">
                  <% if @users.empty? %>
                    イベントの参加者を選択するために、まずはユーザ登録を行ってください
                  <% else %>
                    <%= f.select :participant_ids, @users.map {|u| [u.name, u.id]}, {}, multiple: true , class: 'form-control' %>
                  <% end %>
                </div>
              </div>
              <div class="form-group">
                <div class="col-lg-10 col-lg-offset-2">
                  <%= f.submit '確定', class: 'btn btn-primary btn-lg' %>
                  <%= link_to '戻る', @event, class: 'btn btn-default btn-lg' %>
                </div>
              </div>
            </fieldset>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <% flash.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= key %>"><%= value %></div>
  <% end %>
</div>

app/views/events/show.html.erb
<% provide(:title, 'イベント参照') %>
<% breadcrumb :show_event, @event %>
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="bs-docs-section">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
        <div class="page-header">
          <h1>イベント参照</h1>
        </div>
      </div>
    </div>
  </div>

  <div class="bs-docs-section">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
        <div class="well bs-component">
          <%= form_for @event, :html => { :class => 'form-horizontal', :role => 'form' } do |f| %>
            <fieldset>
              <legend>イベント基本情報</legend>
              <div class="form-group">
                <%= f.label :name, 'イベント名', class: 'col-lg-2 control-label' %>
                <div class="col-lg-10">
                  <%= @event.name %>
                </div>
              </div>
              <div class="form-group">
                <%= f.label :memo, '概要', class: 'col-lg-2 control-label' %>
                <div class="col-lg-10">
                  <%= @event.memo %>
                </div>
              </div>
              <div class="form-group">
                <%= f.label :date, '開催日', class: 'col-lg-2 control-label' %>
                <div class="col-lg-10">
                  <%= @event.formatted_date %>
                </div>
              </div>
              <div class="form-group">
                <%= f.label :participants, '参加者', class: 'col-lg-2 control-label' %>
                <div class="col-lg-10">
                  <% if @event.users.empty? %>
                    イベント参加中のユーザは存在しません
                  <% else %>
                    <ul>
                      <% @event.users.each do |u| %>
                        <li><%= u.name %></li>
                      <% end %>
                    </ul>
                  <% end %>
                </div>
              </div>
            </fieldset>
          <% end %>

          <fieldset>
            <legend>登録済支払情報</legend>
            <% if @event.items.empty? %>
              <div class="form-group">
                <div class="col-lg-10 col-lg-offset-2">
                  登録済支払情報はありません
                </div>
              </div>
            <% else %>
              <% @items.each do |item| %>
                <% unless item.payments.empty? then %>
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <div class="row">
                        <div class="col-xs-7 col-sm-8 col-md-8 col-lg-8 lead">
                          <div class="item_memo">
                            <%= item.memo %>
                          </div>
                        </div>
                        <div class="col-xs-5 col-sm-3 col-md-3 col-lg-3 lead text-right">
                          <div class="item_price">
                            <%= number_with_delimiter(item.price, delimiter: ',') %>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="panel-body">
                      <% item.payments.each do |payment| %>
                        <div class="row<%= ' text-muted' if payment.status %>">
                          <div class="col-xs-5 col-sm-8 col-md-8 col-lg-8">
                            <div class="user_name">
                              <%= payment.participant.user.id == item.user.id ? '★ ' : '　' %>
                              <%= payment.participant.user.name %>
                            </div>
                          </div>
                          <div class="col-xs-5 col-sm-3 col-md-3 col-lg-3 text-right">
                            <div class="payment_price">
                              <%= number_with_delimiter(payment.price, delimiter: ',') %>
                            </div>  
                          </div>
                          <div class="col-xs-2 col-sm-1 col-md-1 col-lg-1">
                            <div class="payment_status">
                              <%= payment.status ? '済' : '　' %>
                            </div>
                          </div>
                        </div>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              <% end %>
              <%= paginate(@items) %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
        <div class="well bs-component">
          <%= link_to 'イベントを編集するよ', {controller: :events, action: :edit}, class: :"btn btn-success btn-lg" %>
          <%= link_to '支払を登録するよ', new_event_item_path(@event), class: :"btn btn-primary btn-lg" %>
          <%= link_to '精算するよ', payments_path(filter_by_event: @event.id), class: :"btn btn-warning btn-lg" %>
          <%= link_to '戻る', events_path, class: 'btn btn-default btn-lg' %>
        </div>
      </div>
    </div>
  </div>
</div>