config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: [:session, :registrations] do
    get '/sign_in', to: 'devise/sessions#new', as: :new_user_session
    get '/sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
    get '/users/edit', to: 'devise/registrations#edit', as: :edit_user
    put '', to: 'devise/registrations#update'
  end
  root 'top#index'

  resources :payments, only: %w(index destroy) do
    collection do
      post 'confirm'
      delete 'bulk_destroy'
    end
  end

  resources :events do
    resources :items
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
  has_many :payments
  before_save :escape_tag

  validates :memo, presence: true, length: { maximum: 20 }
  validates :price, presence: true, numericality: { only_integer: true, greater_than: 0 }

  validates :user_id, presence: true
  validates :event_id, presence: true

  default_scope -> { order('id DESC') }

  private

  def escape_tag
    tags = {
      '<' => '&lt;',
      '>' => '&gt;' }
    tags.each do |key, val|
      memo.gsub!(key, val)
    end
  end
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :participant
  belongs_to :item
  validates :participant_id, presence: true
  validates :item_id, presence: true
  validates :price, presence: true

  default_scope -> { order('item_id DESC, participant_id ASC') }

  def finished
    update_attribute(:status, true)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
    @users = User.all
    @events = Event.all
    payments = Payment.all

    if params[:filter_by_event] && params[:filter_by_event] != 'none'
      payments = payments.reject { |p| p.item.event.id != params[:filter_by_event].to_i }
    end

    if params[:filter_by_user] && params[:filter_by_user] != 'none'
      payments = payments.reject do |p|
        p.item.user.id != params[:filter_by_user].to_i &&
        p.participant.user.id != params[:filter_by_user].to_i
      end
    end

    if params[:only_non_settleup] && params[:only_non_settleup] == 'yes'
      payments = payments.reject { |p| p.status == true }
    end

    @payments = Kaminari.paginate_array(payments).page params[:page] if payments
  end

  def confirm
    @payments = Payment.where(id: params[:payment_ids]).reject { |p| p.status == true }
  end

  def destroy
    payment = Payment.find(params[:id])
    payment.finished
    flash[:success] = '精算が完了しました！'
    redirect_to payments_path
  rescue
    flash[:error] = '不正な操作です。再度やり直して下さい'
    redirect_to payments_path
  end

  def bulk_destroy
    payments = Payment.where(id: params[:payment_ids])
    fail if payments.empty?
    payments.each(&:finished)
    flash[:success] = '精算が完了しました！'
    redirect_to payments_path
  rescue
    flash[:error] = '不正な操作です。再度やり直して下さい'
    redirect_to payments_path
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/confirm.html.erb
<% provide(:title, '精算確認') %>
<% breadcrumb :confirm_payments %>
<div class="container">

  <div class="bs-docs-section">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
        <div class="page-header">
          <h1>精算確認</h1>
        </div>
      </div>
    </div>
  </div>

  <%= form_tag bulk_destroy_payments_path, method: :delete do %>
    <div class="bs-docs-section">
      <fieldset>
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2">
            <% if @payments == nil || @payments.count == 0 %>
              精算対象を選択してね
            <% else %>
              <table class="table table-striped table-hover">
                <thead>
                  <tr>
                    <th>イベント</th>
                    <th>支払元</th>
                    <th>支払先</th>
                    <th>品目</th>
                    <th>金額</th>
                  </tr>
                </thead>
                <tbody>
                  <% @payments.each do |payment| %>
                    <tr>
                      <td><%= hidden_field_tag "payment_ids[]", payment.id %><%= payment.item.event.name %></td>
                      <td><%= payment.participant.user.name %></td>
                      <td><%= payment.item.user.name %></td>
                      <td><%= payment.item.memo %></td>
                      <td><%= payment.price %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            <% end %>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-8 col-lg-offset-2">
            <div class="form-group">
              <% if @payments == nil || @payments.count == 0 %>
              <% else %>
                <%= submit_tag "精算するよ", class: :"btn btn-warning btn-lg" %>
              <% end %>
              <%= link_to "戻る", {controller: :payments}, class: :"btn btn-default btn-lg" %>
            </div>
          </div>
        </div>
      </fieldset>
    </div>
  <% end %>
</div>

app/views/payments/index.html.erb
<% provide(:title, '支払一覧') %>
<% provide(:settleup_form, true) %>
<% breadcrumb :payments %>
<div class="container">

  <div class="bs-docs-section">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
        <div class="page-header">
          <h1>支払一覧</h1>
        </div>
      </div>
    </div>
  </div>

  <%= form_tag 'payments', method: 'get', id: 'list_config' do %>
    <div class="bs-docs-section">
      <fieldset>
        <div class="form-group">
          <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
              <%= label :payment, :filter_by_event, 'イベントでフィルタ', class: 'col-lg-2 control-label' %>
              <div class="col-lg-4">
                <select id='filter_by_event' name='filter_by_event' class="form-control">
                  <option value='none'>しない</option>
                  <% @events.each do |e| %>
                    <option value='<%= e.id %>' <%= 'selected' if e.id == params[:filter_by_event].to_i %>><%= e.name %></option>
                  <% end %>
                </select>
              </div>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
              <%= label :payment, :filter_by_user, 'ユーザでフィルタ', class: 'col-lg-2 control-label' %>
              <div class="col-lg-4">
                <select id='filter_by_user' name='filter_by_user' class="form-control">
                  <option value='none'>しない</option>
                  <% @users.each do |u| %>
                    <option value='<%= u.id %>' <%= 'selected' if u.id == params[:filter_by_user].to_i %>><%= u.name %></option>
                  <% end %>
                </select>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-8 col-lg-offset-2">
            <div class="col-lg-4 col-lg-offset-2">
              <label>
                <input type="checkbox" id="only_non_settleup" name="only_non_settleup" value="yes" <%= 'checked' if 'yes' == params[:only_non_settleup] %>>未精算のみ表示
              </label>
            </div>
            <div class="col-lg-2 col-lg-offset-2">
              <button id="reload" class="btn btn-default">再表示</button>
            </div>
          </div>
        </div>
      </fieldset>
    </div>
  <% end %>

  <%= form_tag 'payments/confirm', id: 'payment_form' do %>
    <div class="bs-docs-section">
      <fieldset>
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2">
            <% if @payments == nil || @payments.count == 0 %>
              支払情報がありません
            <% else %>
              <%= paginate @payments %>
              <table class="footable table table-hover">
                <thead>
                  <tr>
                    <th data-hide="phone">イベント</th>
                    <th data-class="source" data-toggle="true">支払元</th>
                    <th data-class="dest">支払先</th>
                    <th data-hide="phone">品目</th>
                    <th data-class="price">金額</th>
                    <th data-class="status">精算状況</th>
                  </tr>
                </thead>
                <tbody>
                  <% @payments.each do |payment| %>
                    <tr>
                      <td><%= payment.item.event.name %></td>
                      <td><%= payment.participant.user.name %></td>
                      <td><%= payment.item.user.name %></td>
                      <td><%= payment.item.memo %></td>
                      <td><%= number_with_delimiter(payment.price, delimiter: ',') %></td>
                      <% if payment.status? %>
                        <td>精算済</td>
                      <% else %>
                        <td><input type='checkbox' id='payment_<%= payment.id %>' name='payment_ids[]' value='<%= payment.id %>'>精算する</td>
                      <% end %>
                    </tr>
                  <% end %>
                </tbody>
              </table>
              <%= paginate @payments %>
            <% end %>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-8 col-lg-offset-2">
            <div class="form-group">
              <button id="settleup" class="btn btn-warning btn-lg">精算画面へ</button>
              <%= link_to "戻る", :root, class: :"btn btn-default btn-lg" %>
            </div>
          </div>
        </div>
      </fieldset>
    </div>
  <% end %>
</div>